### ISSUE TITLE
Does not properly parse IE 11 in compatibility mode

### ISSUE THREAD

**Issue by laurawhalin** [doomspork/ua_parser#13]
The following user agent is for IE 11 but parses as IE 10. In compatibility mode, the Trident version still corresponds to IE 11 (4 versions behind). 
`Mozilla/5.0 (compatible%3B MSIE 10.0%3B Windows NT 6.1%3B WOW64%3B Trident/7.0%3B)`
And here is a short MS blog about IE 11 user agents. https://blogs.msdn.microsoft.com/ieinternals/2013/09/21/internet-explorer-11s-many-user-agent-strings/
I'll give this issue a try.

**Comment by doomspork** [comment]
@laurawhalin I believe you and I have discussed this before but the issue isn't with this library, it's with the underlying pattern file managed by BrowserScope.  

If you run the same User-Agent through the Ruby UA library you'll get the same results:

```elixir
➜  example git:(master) ✗ pry
[1] pry(main)> require 'user_agent_parser'
=> true
[2] pry(main)> ua = UserAgentParser.parse("Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/7.0;)")
=> #<UserAgentParser::UserAgent IE 10.0 (Windows 7) (Other)>
[3] pry(main)> ua.to_s
=> "IE 10.0"
```

**Comment by doomspork** [comment]
@laurawhalin here is a previous issue I created when I encountered a number of issues with User-Agents, they were all tied to the underlying pattern file: https://github.com/doomspork/ua_parser/issues/12
