### ISSUE TITLE
Regex misses Chrome/Chromium minor patch version

### ISSUE THREAD

**Issue by darrenklein** [doomspork/ua_parser#14]
Hello, thank you so much for this extremely helpful library!

I noticed that the regex used for Chromium/Chrome fails to pick up the minor patch version - this isn't a big deal, but it'd be nice to have it.  Correct me if I'm wrong, but I believe that the regex would need to be:

    - regex: '(Chromium|Chrome)/(\d+)\.(\d+)(?:\.(\d+))(?:\.(\d+))?'

That's line 437 of patterns.yml. Otherwise, that value comes back as `nil`.

What do you think?

**Comment by doomspork** [comment]
@darrenklein I've gone ahead and merged in the @yieldbot change.  Feel free to open a PR with your change 👍

**Comment by darrenklein** [comment]
Great, I've opened a PR.  Again, many thanks for all of your hard work, and for letting me lend a hand!
